### ISSUE TITLE
Crashes When generating the Deep Dark

### ISSUE THREAD

**Issue by ghost** [TTFTCUTS/ATG#1]
If you use the ATG world generator and go to the deep dark the game will crash and give generation errors in the logs.

**Comment by TTFTCUTS** [comment]
It would be helpful if you could supply the errors in question

**Comment by ghost** [comment]
http://pastebin.com/2s96ZgFr

**Comment by TTFTCUTS** [comment]
Interesting. I think Tema might be using the overworld biome provider, and that's causing an issue. The error is mine, but caused by that when it should fall back to ocean instead. Will fall back gracefully instead of crashing next version, and I'll talk to Tema about what's going on.

**Comment by th4umiel** [comment]
I came here to report the same problem: glad to hear I'm not the only one involved :)

**Comment by TTFTCUTS** [comment]
2.0.1 has been out for a few days - does that fix the issue? Note that it has a one time breaking change on ATG's added biomes though.

**Comment by ghost** [comment]
Yes it is fixed, going to close this issue since no problems with the latest version of extra utils and 2.0.1.
