### ISSUE TITLE
Is It Normal?

### ISSUE THREAD

**Issue by ghost** [TTFTCUTS/ATG#3]
it is terrible...
![2017-03-13_15 55 11](https://cloud.githubusercontent.com/assets/24831406/23855135/35f7ea18-07fd-11e7-85fd-93a8bfeb9fcf.png)

**Comment by TTFTCUTS** [comment]
Uhh, that looks like the seed changed somehow or some other serious change took place. What is the game version/mod version/world seed/coordinates, and did you do anything to the world after starting such as moving between versions of the game or any other shenanigans?

I've yet to see anything like this happen with ATG in any of my tests, which leads me to believe some other circumstance changed.

**Comment by ghost** [comment]
game 1.11.2 forge 2255 latest ATG 2.0.1 i didn't change ANYthing i just selected ATG- Alternate option on world generation, enabled bonus chest, then created and it is like this

**Comment by ghost** [comment]
and i use forestry, techreborn and some other mods

**Comment by ghost** [comment]
[fml-client-latest.txt](https://github.com/TTFTCUTS/ATG/files/838248/fml-client-latest.txt)

**Comment by TTFTCUTS** [comment]
World seed and coordinates would be helpful. I believe /seed works on single player still.

Also, is this a thing which is happening consistently, or just that one generation? If you use "re-create world" does it also happen in the copy?

**Comment by kenijey** [comment]
let me try. give me 5 mins

**Comment by ghost** [comment]
-4558210952269863722 x:75 y:111 z:-67

**Comment by ghost** [comment]
okay, it didn't happen when i re create the world. i think it's normal because another mod was stopped world creation because of it's config file. (Roots mod) and it works fine now.

**Comment by ghost** [comment]
I THINK.
but i just looked up to that mods config, nothing wrong. so it shouldn't effected the world creation. 
ah, whatever...

**Comment by TTFTCUTS** [comment]
When I saw the edge exactly aligned to the chunks it made me suspicious that it might be something else. Seems those suspicions were correct.

**Comment by ghost** [comment]
it was just weird

**Comment by ianlavr** [comment]
honestly that looks really cool. i would live there
