### ISSUE TITLE
1.11.2 server side crashing on new chunks

### ISSUE THREAD

**Issue by SDUBZ** [TTFTCUTS/ATG#6]
forge:1.11.2-2282
atg: atg-1.11.2-2.0.1
bop: BiomesOPlenty-1.11.2-6.0.2.2169-universal

was exploring new chunks when i got this crash on my server
crash report:
[crash-2017-04-16_05.10.32-server.txt](https://github.com/TTFTCUTS/ATG/files/924187/crash-2017-04-16_05.10.32-server.txt)

**Comment by TTFTCUTS** [comment]
Well for one there's no actual BoP support in yet so using the two together is pretty pointless at this time, but line 236 there is the forge terrain event bus call for populating ice, and looks like something going wrong in a mob spawning routine. Looks like it's just passing through ATG code.

Pretty sure it's not my fault.

**Comment by SDUBZ** [comment]
oh okay thanks @TTFTCUTS :D i always post just being safe as a server owner you know :D

**Comment by SDUBZ** [comment]
abit more info if you need it

[fml-server-latest.log.txt](https://github.com/TTFTCUTS/ATG/files/937671/fml-server-latest.log.txt)
[fml-server-latest1.log.txt](https://github.com/TTFTCUTS/ATG/files/937672/fml-server-latest1.log.txt)
[crash-2017-04-18_04.17.29-server.txt](https://github.com/TTFTCUTS/ATG/files/937673/crash-2017-04-18_04.17.29-server.txt)

**Comment by ghost** [comment]
so all crashes caused by biomesop ? are you sure about that? because in my crash it crashed with just a few fish mod
