### ISSUE TITLE
1.11.2 crash when loading world

### ISSUE THREAD

**Issue by KristjanKr** [TTFTCUTS/ATG#8]
Game crashes when loading world
Here is log: https://paste.ee/p/9hUTs
Also the game has foamfix and optifine if it matters
forge: 2282
and atg version 2.0,1 for mc 1.11.2

**Comment by TTFTCUTS** [comment]
Somebody is asking the world to generate chunks on another thread... probably optifine's mutli-thread loading stuff. Could you test without that to confirm?

Looks like I'll have to switch to concurrent caching after all.

**Comment by Gyvavaizdis** [comment]
I am also having a similar crash on the 1.10 Coop Life server.
https://gist.github.com/Gyvavaizdis/8f5fa9bae3fde1516630ac790a998430
I am not using Optifine. (was reading prior messages on here)

**Comment by mezz** [comment]
`ChunkCache` is used instead of `World` for things that need to access chunks for render information, and it is used on a render thread, not the main thread. Since modders can call `ChunkCache.getBiome` from the rendering thread, your implementation probably needs to be concurrent.

**Comment by TTFTCUTS** [comment]
Fixed as of 2.1.3, as far as I can tell.
